coverage:
  status:
    project:
      default:
        target: auto
        threshold: "5%"
    patch:
      default:
        target: 85%

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
