// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAewYrLAVb5UOEf_b0DqBjYERx1SIx4Gjk',
    appId: '1:76469425304:web:90e4d4966d48aa1ca2eced',
    messagingSenderId: '76469425304',
    projectId: 'fir-local-config-sample-260a9',
    authDomain: 'fir-local-config-sample-260a9.firebaseapp.com',
    storageBucket: 'fir-local-config-sample-260a9.appspot.com',
    measurementId: 'G-6TCFZ2QVW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7ni0zbQvWpbZXzEUuhAR7ZzznnpXqMk',
    appId: '1:76469425304:android:c13e44e0b9969167a2eced',
    messagingSenderId: '76469425304',
    projectId: 'fir-local-config-sample-260a9',
    storageBucket: 'fir-local-config-sample-260a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI5RRweoAx_7rlCGYpGUxSEKNoJLLwp7U',
    appId: '1:76469425304:ios:fcc1cb2b6efb89e8a2eced',
    messagingSenderId: '76469425304',
    projectId: 'fir-local-config-sample-260a9',
    storageBucket: 'fir-local-config-sample-260a9.appspot.com',
    iosBundleId: 'com.adrianotelesc.firebaselocalconfig.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI5RRweoAx_7rlCGYpGUxSEKNoJLLwp7U',
    appId: '1:76469425304:ios:fcc1cb2b6efb89e8a2eced',
    messagingSenderId: '76469425304',
    projectId: 'fir-local-config-sample-260a9',
    storageBucket: 'fir-local-config-sample-260a9.appspot.com',
    iosBundleId: 'com.adrianotelesc.firebaselocalconfig.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAewYrLAVb5UOEf_b0DqBjYERx1SIx4Gjk',
    appId: '1:76469425304:web:1f512af9c726284ca2eced',
    messagingSenderId: '76469425304',
    projectId: 'fir-local-config-sample-260a9',
    authDomain: 'fir-local-config-sample-260a9.firebaseapp.com',
    storageBucket: 'fir-local-config-sample-260a9.appspot.com',
    measurementId: 'G-J4ZSW0QK38',
  );
}
